### ISSUE TITLE
mimalloc >= 2.0.6 has issues in Windows

### ISSUE THREAD

**Issue by elbaro** [conda-forge/mimalloc-feedstock#22]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The ci build on Windows is failing.

Azure pipeline has 2 windows versions.
- Windows Server 2022 with Visual Studio 2022
- Windows Server 2019 with Visual Studio 2019

Upstream issues
- https://github.com/microsoft/mimalloc/issues/623#issuecomment-1255274872
- https://github.com/microsoft/mimalloc/issues/575
- https://github.com/microsoft/mimalloc/issues/657#issuecomment-1412646519

- In Windows Server 2019, BCryptGenRandom is reportedly worked
- v2.0.6 uses RtlGenRandom by default
- Our ci still fails with v2.0.9 which uses BCryptGenRandom

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by jakirkham** [comment]
Would add [2.0.9 doesn't even seem to build on conda-forge]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=657513&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f )

**Comment by elbaro** [comment]
v2.0.10 fixed windows but broke linux

**Comment by elbaro** [comment]
Windows builds fine in v2.1.1.

**Comment by jakirkham** [comment]
Thanks @elbaro! 🙏

In that case let's migrate to the new version ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4310 ). Hopefully that will clear up the remaining issues
